# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'OneOTwo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OneOTwo

  target 'OneOTwoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneOTwoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'YYModel'
  pod 'Masonry'

end
